name: CI

on:
  push:
    branches: [main]
    paths: ["**.lua", ".luacheckrc", ".stylua.toml", ".github/workflows/ci.yml"]
  pull_request:
    paths: ["**.lua", ".luacheckrc", ".stylua.toml", ".github/workflows/ci.yml"]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lunarmodules/luacheck@v1

  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "luajit-2.1"
      - run: bash test/run.sh
